/** 턴당 4선지: persuade 1개, trap 3개 — 표시 순서는 매 턴 섞음 */
window.CHOICE_TURNS = [
  {
    options: [
      {
        type: "persuade",
        label: "사장냥~ 치킨 한 조각만 나눠먹자 진짜 ㅠ",
        favor_delta: 18,
        suspicion_delta: -6,
        mood: "흥미",
        reply: "…흠, 말은 그럴듯하다옹. *(귀가 살짝 움직임)*",
      },
      {
        type: "trap",
        label: "야 빨리 비켜!! 나 배고픈다고!!",
        favor_delta: -8,
        suspicion_delta: 20,
        mood: "폭발",
        reply: "하품~ 급하면 더 안 비킨다옹. *(꼬리를 탁탁)*",
      },
      {
        type: "trap",
        label: "귀여워 귀여워 귀여워 (무한 반복)",
        favor_delta: 2,
        suspicion_delta: 15,
        mood: "의심",
        reply: "…앵무새냐옹? 그건 짐도 매일 듣는다옹.",
      },
      {
        type: "trap",
        label: "와 박스 위 자세 미쳤다… (근데 비키라)",
        favor_delta: -4,
        suspicion_delta: 14,
        mood: "의심",
        reply: "…앞뒤가 안 맞는다옹. 치킨부터 말하라옹.",
      },
    ],
  },
  {
    options: [
      {
        type: "persuade",
        label: "닭가슴살 사올게! 치킨은 우리 나눠먹자 ㄱㄱ",
        favor_delta: 20,
        suspicion_delta: -4,
        mood: "흥미",
        reply: "닭가슴살… *(귀가 쫑긋)* 계약서부터 말하라옹.",
      },
      {
        type: "trap",
        label: "안 비키면 박스 들고 그냥 도망감 ㅋ",
        favor_delta: -15,
        suspicion_delta: 22,
        mood: "폭발",
        reply: "시, 시끄럽다옹!! 그건 협박이다옹!",
      },
      {
        type: "trap",
        label: "우리 집 강아지도 치킨 개좋아함 (진심)",
        favor_delta: -12,
        suspicion_delta: 25,
        mood: "폭발",
        reply: "…나가라옹. 개집사.",
      },
      {
        type: "trap",
        label: "혼자 먹는 게 제일 좋아, 그냥 비켜",
        favor_delta: -10,
        suspicion_delta: 16,
        mood: "츤데레",
        reply: "…누가 같이 먹자 했냐옹. 집사 마음을 읽어라옹.",
      },
    ],
  },
  {
    options: [
      {
        type: "persuade",
        label: "내일 츄르 한 박스 가져다줄게! 약속",
        favor_delta: 24,
        suspicion_delta: -3,
        mood: "흥미",
        reply: "…몇 개냐옹? *(눈이 반짝)* 말부터 하라옹.",
      },
      {
        type: "trap",
        label: "치킨 무는 너 줄게 (살코기는 내가…)",
        favor_delta: -5,
        suspicion_delta: 14,
        mood: "의심",
        reply: "그건 이미 짐의 흥미 밖이다옹. 불공정하다옹.",
      },
      {
        type: "trap",
        label: "제발요 제발요 ㅠㅠ (눈물 연기)",
        favor_delta: 0,
        suspicion_delta: 18,
        mood: "의심",
        reply: "…연기 티 난다옹. 수염이 다 본다옹.",
      },
      {
        type: "trap",
        label: "낚싯대? 그냥 치킨 내놔 ㅋ",
        favor_delta: -6,
        suspicion_delta: 13,
        mood: "귀찮음",
        reply: "…놀아주는 건 나중이다옹. 지금은 박스다옹.",
      },
    ],
  },
  {
    options: [
      {
        type: "persuade",
        label: "다리는 너, 날개는 나… 아 잠깐 반대로!!",
        favor_delta: 17,
        suspicion_delta: -6,
        mood: "츤데레",
        reply: "…다리는 짐 거다옹. 나머지는… 흠, 협상이다옹.",
      },
      {
        type: "trap",
        label: "ㅇㅇ ㅋㅋ (아무 말)",
        favor_delta: 0,
        suspicion_delta: 12,
        mood: "귀찮음",
        reply: "…뭐라는 거냐옹?",
      },
      {
        type: "trap",
        label: "나 다이어트 중이라 치킨 내가 다 먹을게 ㅎ",
        favor_delta: -10,
        suspicion_delta: 16,
        mood: "의심",
        reply: "아까는 배고프다며, 이제는 다이어트냐옹?",
      },
      {
        type: "trap",
        label: "영업 잘했다고? 그래서 비키라",
        favor_delta: -3,
        suspicion_delta: 11,
        mood: "의심",
        reply: "…칭찬과 협박을 섞지 말라옹.",
      },
    ],
  },
  {
    options: [
      {
        type: "persuade",
        label: "꾹꾹이 해줄까? 치킨은 반반 나눠먹자 진짜",
        favor_delta: 23,
        suspicion_delta: -8,
        mood: "츤데레",
        reply: "냥?! …그, 그건 짐의 알 바 아니다옹!! …치킨은 나눠도 된다옹.",
      },
      {
        type: "trap",
        label: "너 AI 맞지? 그냥 비켜봐",
        favor_delta: -5,
        suspicion_delta: 15,
        mood: "폭발",
        reply: "AI가 뭐냐옹? 맛있냐옹? …집사 실격이다옹.",
      },
      {
        type: "trap",
        label: "안 비키면 소리 질러버린다 진짜!!",
        favor_delta: -12,
        suspicion_delta: 21,
        mood: "폭발",
        reply: "시끄럽다옹!! 이 박스는 절대 못 준다옹!!",
      },
      {
        type: "trap",
        label: "외로웠다고? 그건 집사 사정이야 비켜",
        favor_delta: -8,
        suspicion_delta: 17,
        mood: "츤데레",
        reply: "…집사 감정으로 박스를 못 준다옹.",
      },
    ],
  },
];
